apiVersion: apps/v1
kind: Deployment
metadata:
  name: doku-app
  labels:
    app: doku-app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: doku-app
  template:
    metadata:
      labels:
        app: doku-app
    spec:
      containers:
        - name: doku-app
          image: 96grappe/dokustudy:v2
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
