apiVersion: v1
kind: PersistentVolume
metadata:
  name: doku-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/doku-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doku-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
